combo_type_names = [
    'None',
    'Stairs [A]',
    'Cave (Walk Down) [A]',
    'Water',
    'Armos',
    'Grave',
    'Dock',
    '-Unused_0',
    'Push (Wait)',
    'Push (Heavy)',
    'Push (Heavy, Wait)',
    'Left Statue',
    'Right Statue',
    'Slow Walk',
    'Conveyor Up',
    'Conveyor Down',
    'Conveyor Left',
    'Conveyor Right',
    'Swim Warp [A]',
    'Dive Warp [A]',
    'Ladder or Hookshot',
    'Step->Secrets (Temporary)',
    'Step->Secrets (Permanent)',
    '-Unused_1',
    'Slash',
    'Slash (Item)',
    'Push (Very Heavy)',
    'Push (Very Heavy, Wait)',
    'Pound',
    'Hookshot Grab',
    '-Hookshot Bridge',
    'Damage (1/2 Heart)',
    'Damage (1 Heart)',
    'Damage (2 hearts)',
    'Damage (4 Hearts)',
    'Center Statue',
    'Trap (Horizontal, Line of Sight)',
    'Trap (Vertical, Line of Sight)',
    'Trap (4-Way)',
    'Trap (Horizontal, Constant)',
    'Trap (Vertical, Constant)',
    'Direct Warp [A]',
    'Hookshot Only',
    'Overhead',
    'No Flying Enemies',
    'Magic Mirror (4-Way)',
    'Magic Mirror (Up-Left, Down-Right)',
    'Magic Mirror (Up-Right, Down-Left)',
    'Magic Prism (3-Way)',
    'Magic Prism (4-Way)',
    'Block Magic',
    'Cave (Walk Up) [A]',
    'Eyeball (8-Way A)',
    'Eyeball (8-Way B)',
    'No Jumping Enemies',
    'Bush',
    'Flowers',
    'Tall Grass',
    'Shallow Water',
    'Lock Block (Normal)',
    'Lock Block (Normal, Copycat)',
    'Lock Block (Boss)',
    'Lock Block (Boss, Copycat)',
    'Ladder Only',
    'BS Grave',
    'Treasure Chest (Normal)',
    'Treasure Chest (Normal, Copycat)',
    'Treasure Chest (Locked)',
    'Treasure Chest (Locked, Copycat)',
    'Treasure Chest (Boss)',
    'Treasure Chest (Boss, Copycat)',
    'Reset Room',
    'Save Point',
    'Save-Quit Point',
    'Cave (Walk Down) [B]',
    'Cave (Walk Down) [C]',
    'Cave (Walk Down) [D]',
    'Stairs [B]',
    'Stairs [C]',
    'Stairs [D]',
    'Direct Warp [B]',
    'Direct Warp [C]',
    'Direct Warp [D]',
    'Cave (Walk Up) [B]',
    'Cave (Walk Up) [C]',
    'Cave (Walk Up) [D]',
    'Swim Warp [B]',
    'Swim Warp [C]',
    'Swim Warp [D]',
    'Dive Warp [B]',
    'Dive Warp [C]',
    'Dive Warp [D]',
    'Stairs [Random]',
    'Direct Warp [Random]',
    'Auto Side Warp [A]',
    'Auto Side Warp [B]',
    'Auto Side Warp [C]',
    'Auto Side Warp [D]',
    'Auto Side Warp [Random]',
    'Sensitive Warp [A]',
    'Sensitive Warp [B]',
    'Sensitive Warp [C]',
    'Sensitive Warp [D]',
    'Sensitive Warp [Random]',
    'Step->Secrets (Sensitive, Temp)',
    'Step->Secrets (Sensitive, Perm.)',
    'Step->Next',
    'Step->Next (Same)',
    'Step->Next (All)',
    'Step->Next (Copycat)',
    'No Enemies',
    'Block Arrow (L1)',
    'Block Arrow (L1, L2)',
    'Block Arrow (All)',
    'Block Brang (L1)',
    'Block Brang (L1, L2)',
    'Block Brang (All)',
    'Block Sword Beam',
    'Block All',
    'Block Fireball',
    'Damage (8 hearts)',
    'Damage (16 hearts)',
    'Damage (32 hearts)',
    '-Unused',
    'Spinning Tile (Immediate)',
    '-Unused",',
    'Screen Freeze (Except FFCs)',
    'Screen Freeze (FFCs Only)',
    'No Ground Enemies',
    'Slash->Next',
    'Slash->Next (Item)',
    'Bush->Next',
    'Slash (Continuous)',
    'Slash (Item, Continuous)',
    'Bush (Continuous)',
    'Flowers (Continuous)',
    'Tall Grass (Continuous)',
    'Slash->Next (Continuous)',
    'Slash->Next (Item, Continuous)',
    'Bush->Next (Continuous)',
    'Eyeball (4-Way)',
    'Tall Grass->Next',
    'Script 01',
    'Script 02',
    'Script 03',
    'Script 04',
    'Script 05',
    'Script 06',
    'Script 07',
    'Script 08',
    'Script 09',
    'Script 10',
    'Script 11',
    'Script 12',
    'Script 13',
    'Script 14',
    'Script 15',
    'Script 16',
    'Script 17',
    'Script 18',
    'Script 19',
    'Script 20',
    'Generic',
    'Pitfall',
    'Step->Effects',
]

quest_rules = [
    'SOLIDBLK',
    'NOTMPNORET',
    'ALWAYSRET',
    'MEANTRAPS',
    'BSZELDA',
    'FADE',
    'FADECS5',
    'FASTDNGN',
    'NOLEVEL3FIX',
    'COOLSCROLL',
    'NOSCROLL',
    '4TRI',
    'EXPLICIT_RAFTING',
    'FASTFILL',
    'CAVEEXITNOSTOPMUSIC',
    '3TRI',
    'TIME',
    'FREEFORM',
    'KILLALL',
    'NOFLICKER',
    'CONTFULL_DEP',
    'RLFIX',
    'LENSHINTS',
    'HERODUNGEONPOSFIX',
    'HOLDITEMANIMATION',
    'HESITANTPUSHBLOCKS',
    'HIDECARRIEDITEMS',
    'FFCSCROLL',
    'RAFTLENS',
    'SMOOTHVERTICALSCROLLING',
    'WHIRLWINDMIRROR',
    'NOFLASHDEATH',
    'HOLDNOSTOPMUSIC',
    'FIREPROOFHERO',
    'OUCHBOMBS',
    'NOCLOCKS_DEP',
    'TEMPCLOCKS_DEP',
    'BRKBLSHLDS_DEP',
    'BRKNSHLDTILES',
    'MEANPLACEDTRAPS',
    'PHANTOMPLACEDTRAPS',
    'ALLOWFASTMSG',
    'LINKEDCOMBOS',
    'NOGUYFIRES',
    'HEARTRINGFIX',
    'NOHEARTRING',
    'OVERWORLDTUNIC',
    'SWORDWANDFLIPFIX',
    'ENABLEMAGIC',
    'MAGICWAND_DEP',
    'MAGICCANDLE_DEP',
    'MAGICBOOTS_DEP',
    'NONBUBBLEMEDICINE',
    'NONBUBBLEFAIRIES',
    'NONBUBBLETRIFORCE',
    'NEWENEMYTILES',
    'NOROPE2FLASH_DEP',
    'NOBUBBLEFLASH_DEP',
    'GHINI2BLINK_DEP',
    'BITMAPOFFSETFIX',
    'PHANTOMGHINI2_DEP',
    'Z3BRANG_HSHOT',
    'NOITEMMELEE',
    'SHADOWS',
    'TRANSSHADOWS',
    'QUICKSWORD',
    'BOMBHOLDFIX',
    'EXPANDEDLTM',
    'NOPOTIONCOMBINE_DEP',
    'HEROFLICKER',
    'SHADOWSFLICKER',
    'WALLFLIERS',
    'NOBOMBPALFLASH',
    'HEARTSREQUIREDFIX',
    'PUSHBLOCKCSETFIX',
    'TRANSLUCENTNAYRUSLOVEROCKET_DEP',
    'FLICKERINGNAYRUSLOVEROCKET_DEP',
    'CMBCYCLELAYERS',
    'DMGCOMBOPRI',
    'WARPSIGNOREARRIVALPOINT',
    'LTTPCOLLISION',
    'LTTPWALK',
    'SLOWENEMYANIM_DEP',
    'TRUEARROWS',
    'NOSAVE',
    'NOCONTINUE',
    'QUARTERHEART',
    'NOARRIVALPOINT',
    'NOGUYPOOF',
    'ALLOWMSGBYPASS',
    'NODIVING',
    'LAYER12UNDERCAVE',
    'NOSCROLLCONTINUE',
    'SMARTSCREENSCROLL',
    'RINGAFFECTDAMAGE',
    'ALLOW10RUPEEDROPS_DEP',
    'TRAPPOSFIX',
    'TEMPCANDLELIGHT',
    'REDPOTIONONCE_DEP',
    'OLDSTYLEWARP',
    'NOBORDER',
    'OLDTRIBBLES_DEP',
    'REFLECTROCKS',
    'OLDPICKUP',
    'ENEMIESZAXIS',
    'SAFEENEMYFADE',
    'MORESOUNDS',
    'BRANGPICKUP',
    'HEARTPIECEINCR_DEP',
    'ITEMSONEDGES',
    'EATSMALLSHIELD_DEP',
    'MSGFREEZE',
    'SLASHFLIPFIX',
    'FIREMAGICSPRITE_DEP',
    'SLOWCHARGINGWALK',
    'NOWANDMELEE',
    'SLOWBOMBFUSES_DEP',
    'SWORDMIRROR',
    'SELECTAWPN',
    'LENSSEESENEMIES',
    'INSTABURNFLAGS',
    'DROWN',
    'MSGDISAPPEAR',
    'SUBSCREENOVERSPRITES',
    'BOMBDARKNUTFIX',
    'LONGBOMBBOOM_DEP',
    'OFFSETEWPNCOLLISIONFIX',
    'DMGCOMBOLAYERFIX',
    'ITEMSINPASSAGEWAYS',
    'LOG',
    'FIREPROOFHERO2',
    'NOITEMOFFSET',
    'ITEMBUBBLE',
    'GOTOLESSNOTEQUAL',
    'LADDERANYWHERE',
    'HOOKSHOTLAYERFIX',
    'REPLACEOPENDOORS',
    'OLDLENSORDER',
    'NOFAIRYGUYFIRES',
    'SCRIPTERRLOG',
    'TRIGGERSREPEAT',
    'ENEMIESFLICKER',
    'OVALWIPE',
    'TRIANGLEWIPE',
    'SMASWIPE',
    'NOSOLIDDAMAGECOMBOS',
    'SHOPCHEAT',
    'HOOKSHOTDOWNBUG',
    'OLDHOOKSHOTGRAB',
    'PEAHATCLOCKVULN',
    'VERYFASTSCROLLING',
    'OFFSCREENWEAPONS',
    'BROKENSTATUES',
    'BOMBCHUSUPERBOMB',
    'ITEMPICKUPSETSBELOW',
    'GANONINTRO',
    'MELEEMAGICCOST',
    'OLDMIRRORCOMBOS',
    'BROKENBOOKCOST',
    'OLDSIDEVIEWSPIKES',
    'OLDINFMAGIC',
    'NEVERDISABLEAMMOONSUBSCREEN',
    'ITEMSCRIPTSKEEPRUNNING',
    'SCRIPTSRUNINHEROSTEPFORWARD',
    'SCRIPTDRAWSINCANCELWARP',
    'FIXSCRIPTSDURINGSCROLLING',
    'SCRIPTDRAWSINWARPS',
    'DYINGENEMYESDONTHURTHERO',
    'SIDEVIEWTRIFORCECELLAR',
    'OUTOFBOUNDSENEMIES',
    'EPILEPSY',
    'SCRIPT_FRIENDLY_ENEMY_TYPES',
    'SMARTDROPS',
    'NO_L_R_BUTTON_INVENTORY_SWAP',
    'USE_EX1_EX2_INVENTORYSWAP',
    'NOFASTMODE',
    'OLD_F6',
    'BROKEN_ASKIP_Y_FRAMES',
    'ENEMY_BROKEN_TOP_HALF_SOLIDITY',
    'SIDEVIEWLADDER_FACEUP',
    'ITEMS_IGNORE_SIDEVIEW_PLATFORMS',
    'DOWN_FALL_THROUGH_SIDEVIEW_PLATFORMS',
    'SIDEVIEW_FALLTHROUGH_USES_DRUNK',
    'DOWN_DOESNT_GRAB_LADDERS',
    'DOWNJUMP_FALL_THROUGH_SIDEVIEW_PLATFORMS',
    'OLD_SIDEVIEW_CEILING_COLLISON',
    '0AFRAME_ITEMS_IGNORE_AFRAME_CHANGES',
    'OLD_ENEMY_KNOCKBACK_COLLISION',
    'FADEBLACKWIPE',
    'PASSIVE_SUBSCRIPT_RUNS_DURING_ACTIVE_SUBSCRIPT',
    'DMAP_ACTIVE_RUNS_DURING_ACTIVE_SUBSCRIPT',
    'ANIMATECUSTOMWEAPONS',
    'WEAPONSMOVEOFFSCREEN',
    'CHECKSCRIPTWEAPONOFFSCREENCLIP',
    'SHORTDGNWALK',
    'SCRIPT_WEAPONS_UNIQUE_SPRITES',
    'ANGULAR_REFLECTED_WEAPONS',
    'MIRRORS_USE_WEAPON_CENTER',
    'CUSTOMCOMBOSLAYERS1AND2',
    'BUSHESONLAYERS1AND2',
    'NEW_HERO_MOVEMENT',
    'DISABLE_4WAY_GRIDLOCK',
    'NEW_COMBO_ANIMATION',
    'OLD_STRING_EDITOR_MARGINS',
    'NO_OVERWRITING_HOPPING',
    'DUNGEON_DMAPS_PERM_SECRETS',
    'STRING_FRAME_OLD_WIDTH_HEIGHT',
    'NO_SCROLL_WHILE_IN_AIR',
    'INSTANT_RESPAWN',
    'BROKEN_OVERWORLD_MINIMAP',
    'NO_STUNLOCK',
    'GREATER_MAX_TIME',
    'BROKEN_RING_POWER',
    'NO_OVERWORLD_MAP_CHARTING',
    'DUNGEONS_USE_CLASSIC_CHARTING',
    'ARROWS_ALWAYS_PENETRATE',
    'SWORDBEAMS_ALWAYS_PENETRATE',
    'SET_XBUTTON_ITEMS',
    'SMARTER_WATER',
    'NO_HOPPING',
    'NO_SOLID_SWIM',
    'WATER_ON_LAYER_1',
    'WATER_ON_LAYER_2',
    'SHALLOW_SENSITIVE',
    'SMARTER_SMART_SCROLL',
    'INSTANT_CONTINUE',
    'NONHEAVY_BLOCKTRIGGER_PERM',
    'SET_YBUTTON_ITEMS',
    'CORRECTED_EW_BRANG_ANIM',
    'SCRIPT_WRITING_HEROSTEP_DOESNT_CARRY_OVER',
    'OVERHEAD_COMBOS_L1_L2',
    'ALLOW_EDITING_COMBO_0',
    'OLD_CHEST_COLLISION',
    'AUTOCOMBO_LAYER_1',
    'AUTOCOMBO_LAYER_2',
    'TRUEFIXEDBOMBSHIELD',
    'BOMBSPIERCESHIELD',
    'BROKEN_HORIZONTAL_WEAPON_ANIM',
    'NEW_DARKROOM',
    'NEWDARK_L6',
    'ENEMIES_SECRET_ONLY_16_31',
    'SCREEN80_OWN_MUSIC',
    'OLDCS2',
    'HARDCODED_ENEMY_ANIMS',
    'OLD_ITEMDATA_SCRIPT_TIMING',
    'SIDESWIM',
    'SIDESWIMDIR',
    'PUSHBLOCK_LAYER_1_2',
    'NEWDARK_SCROLLEDGE',
    'STEPTEMP_SECRET_ONLY_16_31',
    'ALLTRIG_PERMSEC_NO_TEMP',
    'HARDCODED_LITEM_LTMS',
    'NO_BOTTLE_IF_ANY_COUNTER_FULL',
    'LIGHTBEAM_TRANSPARENT',
    'CANDLES_SHARED_LIMIT',
    'OLD_RESPAWN_POINTS',
    'HOOKSHOTALLLAYER',
    'ANONE_NOANIM',
    'BLOCKHOLE_SAME_ONLY',
    'SWITCHOBJ_RUN_SCRIPT',
    'ITEMCOMBINE_NEW_PSTR',
    'ITEMCOMBINE_CONTINUOUS',
    'SCC_ITEM_COMBINES_ITEMS',
    'SCROLLING_KILLS_CHARGE',
    'CUSTOMWEAPON_IGNORE_COST',
    'BLOCKS_DONT_LOCK_OTHER_LAYERS',
    'FIXED_FAIRY_LIMIT',
    'FAIRYDIR',
    'ARROWCLIP',
    'CONT_SWORD_TRIGGERS',
    'OLD_210_WATER',
    '8WAY_SHOT_SFX',
    'COPIED_SWIM_SPRITES',
    'WRONG_BRANG_TRAIL_DIR',
    '192b163_WARP',
    '210_WARPRETURN',
    'LESS_AWFUL_SIDESPIKES',
    'OLD_LADDER_ITEM_SIDEVIEW',
    'OLD_SECRETMONEY',
    'OLD_DOORREPAIR',
    'OLD_POTION_OR_HC',
    'NO_LANMOLA_RINGLEADER',
    'HARDCODED_BS_PATRA',
    'PATRAS_USE_HARDCODED_OFFSETS',
    'BROKEN_BIG_ENEMY_ANIMATION',
    'BROKEN_ATTRIBUTE_31_32',
    'CAN_PLACE_GANON',
    'CAN_PLACE_TRAPS',
    'FIND_CLOSEST_BAIT',
    'OLD_FLAMETRAIL_DURATION',
    'PERMANENT_WHISTLE_SECRETS',
    'SMARTER_DROPS',
    'WAVY_NO_EPILEPSY',
    'WAVY_NO_EPILEPSY_2',
    'DYING_ENEMIES_IGNORE_STUN',
    'SHOP_ITEMS_VANISH',
    'ANGULAR_REFLECT_BROKEN',
    'CSET1_LEVEL',
    'CSET5_LEVEL',
    'CSET7_LEVEL',
    'CSET8_LEVEL',
    'FADECS1',
    'FADECS7',
    'FADECS8',
    'FADECS9',
    'UNBEATABLES_DONT_KEEP_DEAD',
    'NO_LEAVE_ONE_ENEMY_ALIVE_TRICK',
    'OLD_BRIDGE_COMBOS',
    'BROKEN_Z3_ANIMATION',
    'OLD_TILE_INITIALIZATION',
    'FLUCTUATING_ENEMY_JUMP',
    'SPRITE_JUMP_IS_TRUNCATED',
    'BUGGY_BUGGY_SLASH_TRIGGERS',
    'OLD_DRAWOFFSET',
    'BROKEN_DRAWSCREEN_FUNCTIONS',
    'ENEMY_DROPS_USE_HITOFFSETS',
    'BROKEN_ITEM_CARRYING',
    'LEEVERS_DONT_OBEY_STUN',
    'QUAKE_STUNS_LEEVERS',
    'GANON_CANT_SPAWN_ON_CONTINUE',
    'WIZZROBES_DONT_OBEY_STUN',
    'OLD_BUG_NET',
    'MANHANDLA_BLOCK_SFX',
    'GRASS_SENSITIVE',
    'BETTER_RAFT',
    'BETTER_RAFT_2',
    'RAFT_SOUND',
    'WARPS_RESTART_DMAPSCRIPT',
    'DMAP_0_CONTINUE_BUG',
    'SCRIPT_WARPS_DMAP_SCRIPT_TOGGLE',
    'OLD_SCRIPTED_KNOCKBACK',
    'OLD_KEESE_Z_AXIS',
    'POLVIRE_NO_SHADOW',
    'CONVEYORS_L1_L2',
    'CUSTOMCOMBOS_EVERY_LAYER',
    'SUBSCR_BACKWARDS_ID_ORDER',
    'FASTCOUNTERDRAIN',
    'OLD_LOCKBLOCK_COLLISION',
    'DECO_2_YOFFSET',
    'SCREENSTATE_80s_BUG',
    'AUTOCOMBO_ANY_LAYER',
    'GOHMA_UNDAMAGED_BUG',
    'FFCPRELOAD_BUGGED_LOAD',
    'SWITCHES_AFFECT_MOVINGBLOCKS',
    'BROKEN_GETPIXEL_VALUE',
    'NO_LIFT_SPRITE',
    'OLD_SIDEVIEW_LANDING_CODE',
    'OLD_FFC_SPEED_CAP',
    'OLD_WIZZROBE_SUBMERGING',
    'OLD_FFC_FUNCTIONALITY',
    'OLD_SHALLOW_SFX',
    'PARSER_250DIVISION',
    'PARSER_NO_LOGGING',
    'PARSER_SHORT_CIRCUIT',
    'PARSER_BOOL_TRUE_DECIMAL',
    'SPRITEXY_IS_FLOAT',
    'PARSER_TRUE_INT_SIZE',
    'WPNANIMFIX',
    'NOSCRIPTSDURINGSCROLL',
    'OLDSPRITEDRAWS',
    'WEAPONSHADOWS',
    'ITEMSHADOWS',
    'OLDEWPNPARENT',
    'OLDCREATEBITMAP_ARGS',
    'OLDQUESTMISC',
    'PARSER_FORCE_INLINE',
    'CLEARINITDONSCRIPTCHANGE',
    'NOFFCWAITDRAW',
    'NOITEMWAITDRAW',
    'TRACESCRIPTIDS',
    'FIXDRUNKINPUTS',
    'PARSER_BINARY_32BIT',
    'ALWAYS_DEALLOCATE_ARRAYS',
    'ONDEATH_RUNS_AFTER_DEATH_ANIM',
    'DISALLOW_SETTING_RAFTING',
    'WEAPONS_EXTRA_FRAME',
    '250WRITEEDEFSCRIPT',
    'SETENEMYWEAPONSPRITESONWPNCHANGE',
    'BROKENCHARINTDRAWING',
    'WRITING_NPC_WEAPON_UNIQUE_SPRITES',
    'COMBOSCRIPTS_LAYER_0',
    'COMBOSCRIPTS_LAYER_1',
    'COMBOSCRIPTS_LAYER_2',
    'COMBOSCRIPTS_LAYER_3',
    'COMBOSCRIPTS_LAYER_4',
    'COMBOSCRIPTS_LAYER_5',
    'COMBOSCRIPTS_LAYER_6',
    'OLD_INIT_SCRIPT_TIMING',
    'DO_NOT_DEALLOCATE_INIT_AND_SAVELOAD_ARRAYS',
    'BITMAP_AND_FILESYSTEM_PATHS_ALWAYS_RELATIVE',
    'PARSER_STRINGSWITCH_INSENSITIVE',
    'OLD_SLASHNEXT_SECRETS',
    'STEP_IS_FLOAT',
    'OLDMAPDATAFLAGS',
    'OLD_PRINTF_ARGS',
    'PASSIVE_SUBSCRIPT_RUNS_WHEN_GAME_IS_FROZEN',
    'WRITE_ENTRYPOINTS_AFFECTS_HEROCLASS',
    'LOG_INVALID_UID_LOAD',
    'COMBODATA_INITD_MULT_TENK',
    'ZS_NO_NEG_ARRAY',
]
