def fill_holes(arr):
    new_arr = []
    for value in arr:
        if isinstance(value, tuple):
            v, jump_index = value
            while len(new_arr) < jump_index:
                new_arr.append(None)
            new_arr.append(v)
        else:
            new_arr.append(value)
    return new_arr


combo_type_names = [
    'None',
    'Stairs [A]',
    'Cave (Walk Down) [A]',
    'Water',
    'Armos',
    'Grave',
    'Dock',
    '-Unused_0',
    'Push (Wait)',
    'Push (Heavy)',
    'Push (Heavy, Wait)',
    'Left Statue',
    'Right Statue',
    'Slow Walk',
    'Conveyor Up',
    'Conveyor Down',
    'Conveyor Left',
    'Conveyor Right',
    'Swim Warp [A]',
    'Dive Warp [A]',
    'Ladder or Hookshot',
    'Step->Secrets (Temporary)',
    'Step->Secrets (Permanent)',
    '-Unused_1',
    'Slash',
    'Slash (Item)',
    'Push (Very Heavy)',
    'Push (Very Heavy, Wait)',
    'Pound',
    'Hookshot Grab',
    '-Hookshot Bridge',
    'Damage (1/2 Heart)',
    'Damage (1 Heart)',
    'Damage (2 hearts)',
    'Damage (4 Hearts)',
    'Center Statue',
    'Trap (Horizontal, Line of Sight)',
    'Trap (Vertical, Line of Sight)',
    'Trap (4-Way)',
    'Trap (Horizontal, Constant)',
    'Trap (Vertical, Constant)',
    'Direct Warp [A]',
    'Hookshot Only',
    'Overhead',
    'No Flying Enemies',
    'Magic Mirror (4-Way)',
    'Magic Mirror (Up-Left, Down-Right)',
    'Magic Mirror (Up-Right, Down-Left)',
    'Magic Prism (3-Way)',
    'Magic Prism (4-Way)',
    'Block Magic',
    'Cave (Walk Up) [A]',
    'Eyeball (8-Way A)',
    'Eyeball (8-Way B)',
    'No Jumping Enemies',
    'Bush',
    'Flowers',
    'Tall Grass',
    'Shallow Water',
    'Lock Block (Normal)',
    'Lock Block (Normal, Copycat)',
    'Lock Block (Boss)',
    'Lock Block (Boss, Copycat)',
    'Ladder Only',
    'BS Grave',
    'Treasure Chest (Normal)',
    'Treasure Chest (Normal, Copycat)',
    'Treasure Chest (Locked)',
    'Treasure Chest (Locked, Copycat)',
    'Treasure Chest (Boss)',
    'Treasure Chest (Boss, Copycat)',
    'Reset Room',
    'Save Point',
    'Save-Quit Point',
    'Cave (Walk Down) [B]',
    'Cave (Walk Down) [C]',
    'Cave (Walk Down) [D]',
    'Stairs [B]',
    'Stairs [C]',
    'Stairs [D]',
    'Direct Warp [B]',
    'Direct Warp [C]',
    'Direct Warp [D]',
    'Cave (Walk Up) [B]',
    'Cave (Walk Up) [C]',
    'Cave (Walk Up) [D]',
    'Swim Warp [B]',
    'Swim Warp [C]',
    'Swim Warp [D]',
    'Dive Warp [B]',
    'Dive Warp [C]',
    'Dive Warp [D]',
    'Stairs [Random]',
    'Direct Warp [Random]',
    'Auto Side Warp [A]',
    'Auto Side Warp [B]',
    'Auto Side Warp [C]',
    'Auto Side Warp [D]',
    'Auto Side Warp [Random]',
    'Sensitive Warp [A]',
    'Sensitive Warp [B]',
    'Sensitive Warp [C]',
    'Sensitive Warp [D]',
    'Sensitive Warp [Random]',
    'Step->Secrets (Sensitive, Temp)',
    'Step->Secrets (Sensitive, Perm.)',
    'Step->Next',
    'Step->Next (Same)',
    'Step->Next (All)',
    'Step->Next (Copycat)',
    'No Enemies',
    'Block Arrow (L1)',
    'Block Arrow (L1, L2)',
    'Block Arrow (All)',
    'Block Brang (L1)',
    'Block Brang (L1, L2)',
    'Block Brang (All)',
    'Block Sword Beam',
    'Block All',
    'Block Fireball',
    'Damage (8 hearts)',
    'Damage (16 hearts)',
    'Damage (32 hearts)',
    '-Unused',
    'Spinning Tile (Immediate)',
    '-Unused",',
    'Screen Freeze (Except FFCs)',
    'Screen Freeze (FFCs Only)',
    'No Ground Enemies',
    'Slash->Next',
    'Slash->Next (Item)',
    'Bush->Next',
    'Slash (Continuous)',
    'Slash (Item, Continuous)',
    'Bush (Continuous)',
    'Flowers (Continuous)',
    'Tall Grass (Continuous)',
    'Slash->Next (Continuous)',
    'Slash->Next (Item, Continuous)',
    'Bush->Next (Continuous)',
    'Eyeball (4-Way)',
    'Tall Grass->Next',
    'Script 01',
    'Script 02',
    'Script 03',
    'Script 04',
    'Script 05',
    'Script 06',
    'Script 07',
    'Script 08',
    'Script 09',
    'Script 10',
    'Script 11',
    'Script 12',
    'Script 13',
    'Script 14',
    'Script 15',
    'Script 16',
    'Script 17',
    'Script 18',
    'Script 19',
    'Script 20',
    'Generic',
    'Pitfall',
    'Step->Effects',
]


quest_rules = fill_holes([
    'qr_SOLIDBLK',
    'qr_NOTMPNORET',
    'qr_ALWAYSRET',
    'qr_MEANTRAPS',
    'qr_BSZELDA',
    'qr_FADE',
    'qr_FADECS5',
    'qr_FASTDNGN',
    'qr_NOLEVEL3FIX',
    'qr_COOLSCROLL',
    'qr_NOSCROLL',
    'qr_4TRI',
    'qr_EXPLICIT_RAFTING',
    'qr_FASTFILL',
    'qr_CAVEEXITNOSTOPMUSIC',
    'qr_3TRI',
    'qr_TIME',
    'qr_FREEFORM',
    'qr_KILLALL',
    'qr_NOFLICKER',
    'qr_CONTFULL_DEP',
    'qr_RLFIX',
    'qr_LENSHINTS',
    'qr_HERODUNGEONPOSFIX',
    'qr_HOLDITEMANIMATION',
    'qr_HESITANTPUSHBLOCKS',
    'qr_HIDECARRIEDITEMS',
    'qr_FFCSCROLL',
    'qr_RAFTLENS',
    'qr_SMOOTHVERTICALSCROLLING',
    'qr_WHIRLWINDMIRROR',
    'qr_NOFLASHDEATH',
    'qr_HOLDNOSTOPMUSIC',
    'qr_FIREPROOFHERO',
    'qr_OUCHBOMBS',
    'qr_NOCLOCKS_DEP',
    'qr_TEMPCLOCKS_DEP',
    'qr_BRKBLSHLDS_DEP',
    'qr_BRKNSHLDTILES',
    'qr_MEANPLACEDTRAPS',
    'qr_PHANTOMPLACEDTRAPS',
    'qr_ALLOWFASTMSG',
    'qr_LINKEDCOMBOS',
    'qr_NOGUYFIRES',
    'qr_HEARTRINGFIX',
    'qr_NOHEARTRING',
    'qr_OVERWORLDTUNIC',
    'qr_SWORDWANDFLIPFIX',
    'qr_ENABLEMAGIC',
    'qr_MAGICWAND_DEP',
    'qr_MAGICCANDLE_DEP',
    'qr_MAGICBOOTS_DEP',
    'qr_NONBUBBLEMEDICINE',
    'qr_NONBUBBLEFAIRIES',
    'qr_NONBUBBLETRIFORCE',
    'qr_NEWENEMYTILES',
    'qr_NOROPE2FLASH_DEP',
    'qr_NOBUBBLEFLASH_DEP',
    'qr_GHINI2BLINK_DEP',
    'qr_BITMAPOFFSETFIX',
    'qr_PHANTOMGHINI2_DEP',
    'qr_Z3BRANG_HSHOT',
    'qr_NOITEMMELEE',
    'qr_SHADOWS',
    'qr_TRANSSHADOWS',
    'qr_QUICKSWORD',
    'qr_BOMBHOLDFIX',
    'qr_EXPANDEDLTM',
    'qr_NOPOTIONCOMBINE_DEP',
    'qr_HEROFLICKER',
    'qr_SHADOWSFLICKER',
    'qr_WALLFLIERS',
    'qr_NOBOMBPALFLASH',
    'qr_HEARTSREQUIREDFIX',
    'qr_PUSHBLOCKCSETFIX',
    'qr_TRANSLUCENTNAYRUSLOVEROCKET_DEP',
    'qr_FLICKERINGNAYRUSLOVEROCKET_DEP',
    'qr_CMBCYCLELAYERS',
    'qr_DMGCOMBOPRI',
    'qr_WARPSIGNOREARRIVALPOINT',
    'qr_LTTPCOLLISION',
    'qr_LTTPWALK',
    'qr_SLOWENEMYANIM_DEP',
    'qr_TRUEARROWS',
    'qr_NOSAVE',
    'qr_NOCONTINUE',
    'qr_QUARTERHEART',
    'qr_NOARRIVALPOINT',
    'qr_NOGUYPOOF',
    'qr_ALLOWMSGBYPASS',
    'qr_NODIVING',
    'qr_LAYER12UNDERCAVE',
    'qr_NOSCROLLCONTINUE',
    'qr_SMARTSCREENSCROLL',
    'qr_RINGAFFECTDAMAGE',
    'qr_ALLOW10RUPEEDROPS_DEP',
    'qr_TRAPPOSFIX',
    'qr_TEMPCANDLELIGHT',
    'qr_REDPOTIONONCE_DEP',
    'qr_OLDSTYLEWARP',
    'qr_NOBORDER',
    'qr_OLDTRIBBLES_DEP',
    'qr_REFLECTROCKS',
    'qr_OLDPICKUP',
    'qr_ENEMIESZAXIS',
    'qr_SAFEENEMYFADE',
    'qr_MORESOUNDS',
    'qr_BRANGPICKUP',
    'qr_HEARTPIECEINCR_DEP',
    'qr_ITEMSONEDGES',
    'qr_EATSMALLSHIELD_DEP',
    'qr_MSGFREEZE',
    'qr_SLASHFLIPFIX',
    'qr_FIREMAGICSPRITE_DEP',
    'qr_SLOWCHARGINGWALK',
    'qr_NOWANDMELEE',
    'qr_SLOWBOMBFUSES_DEP',
    'qr_SWORDMIRROR',
    'qr_SELECTAWPN',
    'qr_LENSSEESENEMIES',
    'qr_INSTABURNFLAGS',
    'qr_DROWN',
    'qr_MSGDISAPPEAR',
    'qr_SUBSCREENOVERSPRITES',
    'qr_BOMBDARKNUTFIX',
    'qr_LONGBOMBBOOM_DEP',
    'qr_OFFSETEWPNCOLLISIONFIX',
    'qr_DMGCOMBOLAYERFIX',
    'qr_ITEMSINPASSAGEWAYS',
    'qr_LOG',
    'qr_FIREPROOFHERO2',
    'qr_NOITEMOFFSET',
    'qr_ITEMBUBBLE',
    'qr_GOTOLESSNOTEQUAL',
    'qr_LADDERANYWHERE',
    'qr_HOOKSHOTLAYERFIX',
    'qr_REPLACEOPENDOORS',
    'qr_OLDLENSORDER',
    'qr_NOFAIRYGUYFIRES',
    'qr_SCRIPTERRLOG',
    'qr_TRIGGERSREPEAT',
    'qr_ENEMIESFLICKER',
    'qr_OVALWIPE',
    'qr_TRIANGLEWIPE',
    'qr_SMASWIPE',
    'qr_NOSOLIDDAMAGECOMBOS',
    'qr_SHOPCHEAT',
    'qr_HOOKSHOTDOWNBUG',
    'qr_OLDHOOKSHOTGRAB',
    'qr_PEAHATCLOCKVULN',
    'qr_VERYFASTSCROLLING',
    'qr_OFFSCREENWEAPONS',
    'qr_BROKENSTATUES',
    'qr_BOMBCHUSUPERBOMB',
    'qr_ITEMPICKUPSETSBELOW',
    'qr_GANONINTRO',
    'qr_MELEEMAGICCOST',
    'qr_OLDMIRRORCOMBOS',
    'qr_BROKENBOOKCOST',
    'qr_OLDSIDEVIEWSPIKES',
    'qr_OLDINFMAGIC',
    'qr_NEVERDISABLEAMMOONSUBSCREEN',
    'qr_ITEMSCRIPTSKEEPRUNNING',
    'qr_SCRIPTSRUNINHEROSTEPFORWARD',
    'qr_SCRIPTDRAWSINCANCELWARP',
    'qr_FIXSCRIPTSDURINGSCROLLING',
    'qr_SCRIPTDRAWSINWARPS',
    'qr_DYINGENEMYESDONTHURTHERO',
    'qr_SIDEVIEWTRIFORCECELLAR',
    'qr_OUTOFBOUNDSENEMIES',
    'qr_EPILEPSY',
    'qr_SCRIPT_FRIENDLY_ENEMY_TYPES',
    'qr_SMARTDROPS',
    'qr_NO_L_R_BUTTON_INVENTORY_SWAP',
    'qr_USE_EX1_EX2_INVENTORYSWAP',
    'qr_NOFASTMODE',
    'qr_OLD_F6',
    'qr_BROKEN_ASKIP_Y_FRAMES',
    'qr_ENEMY_BROKEN_TOP_HALF_SOLIDITY',
    'qr_SIDEVIEWLADDER_FACEUP',
    'qr_ITEMS_IGNORE_SIDEVIEW_PLATFORMS',
    'qr_DOWN_FALL_THROUGH_SIDEVIEW_PLATFORMS',
    'qr_SIDEVIEW_FALLTHROUGH_USES_DRUNK',
    'qr_DOWN_DOESNT_GRAB_LADDERS',
    'qr_DOWNJUMP_FALL_THROUGH_SIDEVIEW_PLATFORMS',
    'qr_OLD_SIDEVIEW_CEILING_COLLISON',
    'qr_0AFRAME_ITEMS_IGNORE_AFRAME_CHANGES',
    'qr_OLD_ENEMY_KNOCKBACK_COLLISION',
    'qr_FADEBLACKWIPE',
    'qr_PASSIVE_SUBSCRIPT_RUNS_DURING_ACTIVE_SUBSCRIPT',
    'qr_DMAP_ACTIVE_RUNS_DURING_ACTIVE_SUBSCRIPT',
    'qr_ANIMATECUSTOMWEAPONS',
    'qr_WEAPONSMOVEOFFSCREEN',
    'qr_CHECKSCRIPTWEAPONOFFSCREENCLIP',
    'qr_SHORTDGNWALK',
    'qr_SCRIPT_WEAPONS_UNIQUE_SPRITES',
    'qr_ANGULAR_REFLECTED_WEAPONS',
    'qr_MIRRORS_USE_WEAPON_CENTER',
    'qr_CUSTOMCOMBOSLAYERS1AND2',
    'qr_BUSHESONLAYERS1AND2',
    'qr_NEW_HERO_MOVEMENT',
    'qr_DISABLE_4WAY_GRIDLOCK',
    'qr_NEW_COMBO_ANIMATION',
    'qr_OLD_STRING_EDITOR_MARGINS',
    'qr_NO_OVERWRITING_HOPPING',
    'qr_DUNGEON_DMAPS_PERM_SECRETS',
    'qr_STRING_FRAME_OLD_WIDTH_HEIGHT',
    'qr_NO_SCROLL_WHILE_IN_AIR',
    'qr_INSTANT_RESPAWN',
    'qr_BROKEN_OVERWORLD_MINIMAP',
    'qr_NO_STUNLOCK',
    'qr_GREATER_MAX_TIME',
    'qr_BROKEN_RING_POWER',
    'qr_NO_OVERWORLD_MAP_CHARTING',
    'qr_DUNGEONS_USE_CLASSIC_CHARTING',
    'qr_ARROWS_ALWAYS_PENETRATE',
    'qr_SWORDBEAMS_ALWAYS_PENETRATE',
    'qr_SET_XBUTTON_ITEMS',
    'qr_SMARTER_WATER',
    'qr_NO_HOPPING',
    'qr_NO_SOLID_SWIM',
    'qr_WATER_ON_LAYER_1',
    'qr_WATER_ON_LAYER_2',
    'qr_SHALLOW_SENSITIVE',
    'qr_SMARTER_SMART_SCROLL',
    'qr_INSTANT_CONTINUE',
    'qr_NONHEAVY_BLOCKTRIGGER_PERM',
    'qr_SET_YBUTTON_ITEMS',
    'qr_CORRECTED_EW_BRANG_ANIM',
    'qr_SCRIPT_WRITING_HEROSTEP_DOESNT_CARRY_OVER',
    'qr_OVERHEAD_COMBOS_L1_L2',
    'qr_ALLOW_EDITING_COMBO_0',
    'qr_OLD_CHEST_COLLISION',
    'qr_AUTOCOMBO_LAYER_1',
    'qr_AUTOCOMBO_LAYER_2',
    'qr_TRUEFIXEDBOMBSHIELD',
    'qr_BOMBSPIERCESHIELD',
    'qr_BROKEN_HORIZONTAL_WEAPON_ANIM',
    'qr_NEW_DARKROOM',
    'qr_NEWDARK_L6',
    'qr_ENEMIES_SECRET_ONLY_16_31',
    'qr_SCREEN80_OWN_MUSIC',
    'qr_OLDCS2',
    'qr_HARDCODED_ENEMY_ANIMS',
    'qr_OLD_ITEMDATA_SCRIPT_TIMING',
    'qr_SIDESWIM',
    'qr_SIDESWIMDIR',
    'qr_PUSHBLOCK_LAYER_1_2',
    'qr_NEWDARK_SCROLLEDGE',
    'qr_STEPTEMP_SECRET_ONLY_16_31',
    'qr_ALLTRIG_PERMSEC_NO_TEMP',
    'qr_HARDCODED_LITEM_LTMS',
    'qr_NO_BOTTLE_IF_ANY_COUNTER_FULL',
    'qr_LIGHTBEAM_TRANSPARENT',
    'qr_CANDLES_SHARED_LIMIT',
    'qr_OLD_RESPAWN_POINTS',
    'qr_HOOKSHOTALLLAYER',
    'qr_ANONE_NOANIM',
    'qr_BLOCKHOLE_SAME_ONLY',
    'qr_SWITCHOBJ_RUN_SCRIPT',
    'qr_ITEMCOMBINE_NEW_PSTR',
    'qr_ITEMCOMBINE_CONTINUOUS',
    'qr_SCC_ITEM_COMBINES_ITEMS',
    'qr_SCROLLING_KILLS_CHARGE',
    'qr_CUSTOMWEAPON_IGNORE_COST',
    'qr_BLOCKS_DONT_LOCK_OTHER_LAYERS',
    'qr_SCC_GOTO_RESPECTS_CONTFLAG',
    'qr_BROKEN_KEEPOLD_FLAG',
    'qr_KEEPOLD_APPLIES_RETROACTIVELY',
    'qr_PASSIVE_ITEM_SCRIPT_ONLY_HIGHEST',
    'qr_OLD_HALF_MAGIC',
    'qr_LEVEL_RESTART_CONT_POINT',
    'qr_SUBSCR_OLD_SELECTOR',
    'qr_OLD_FAIRY_LIMIT',
    'qr_FAIRYDIR',
    'qr_ARROWCLIP',
    'qr_CONT_SWORD_TRIGGERS',
    'qr_OLD_210_WATER',
    'qr_8WAY_SHOT_SFX',
    'qr_COPIED_SWIM_SPRITES',
    'qr_WRONG_BRANG_TRAIL_DIR',
    'qr_192b163_WARP',
    'qr_210_WARPRETURN',
    'qr_LESS_AWFUL_SIDESPIKES',
    'qr_OLD_LADDER_ITEM_SIDEVIEW',
    'qr_OLD_SECRETMONEY',
    'qr_OLD_DOORREPAIR',
    'qr_OLD_POTION_OR_HC',
    'qr_NO_LANMOLA_RINGLEADER',
    'qr_HARDCODED_BS_PATRA',
    'qr_PATRAS_USE_HARDCODED_OFFSETS',
    'qr_BROKEN_BIG_ENEMY_ANIMATION',
    'qr_BROKEN_ATTRIBUTE_31_32',
    'qr_CAN_PLACE_GANON',
    'qr_CAN_PLACE_TRAPS',
    'qr_FIND_CLOSEST_BAIT',
    'qr_OLD_FLAMETRAIL_DURATION',
    'qr_PERMANENT_WHISTLE_SECRETS',
    'qr_SMARTER_DROPS',
    'qr_WAVY_NO_EPILEPSY',
    'qr_WAVY_NO_EPILEPSY_2',
    'qr_DYING_ENEMIES_IGNORE_STUN',
    'qr_SHOP_ITEMS_VANISH',
    'qr_ANGULAR_REFLECT_BROKEN',
    'qr_CSET1_LEVEL',
    'qr_CSET5_LEVEL',
    'qr_CSET7_LEVEL',
    'qr_CSET8_LEVEL',
    'qr_FADECS1',
    'qr_FADECS7',
    'qr_FADECS8',
    'qr_FADECS9',
    'qr_UNBEATABLES_DONT_KEEP_DEAD',
    'qr_NO_LEAVE_ONE_ENEMY_ALIVE_TRICK',
    'qr_OLD_BRIDGE_COMBOS',
    'qr_BROKEN_Z3_ANIMATION',
    'qr_OLD_TILE_INITIALIZATION',
    'qr_FLUCTUATING_ENEMY_JUMP',
    'qr_SPRITE_JUMP_IS_TRUNCATED',
    'qr_BUGGY_BUGGY_SLASH_TRIGGERS',
    'qr_OLD_DRAWOFFSET',
    'qr_BROKEN_DRAWSCREEN_FUNCTIONS',
    'qr_ENEMY_DROPS_USE_HITOFFSETS',
    'qr_BROKEN_ITEM_CARRYING',
    'qr_LEEVERS_DONT_OBEY_STUN',
    'qr_QUAKE_STUNS_LEEVERS',
    'qr_GANON_CANT_SPAWN_ON_CONTINUE',
    'qr_WIZZROBES_DONT_OBEY_STUN',
    'qr_OLD_BUG_NET',
    'qr_MANHANDLA_BLOCK_SFX',
    'qr_GRASS_SENSITIVE',
    'qr_BETTER_RAFT',
    'qr_BETTER_RAFT_2',
    'qr_RAFT_SOUND',
    'qr_WARPS_RESTART_DMAPSCRIPT',
    'qr_DMAP_0_CONTINUE_BUG',
    'qr_SCRIPT_WARPS_DMAP_SCRIPT_TOGGLE',
    'qr_OLD_SCRIPTED_KNOCKBACK',
    'qr_OLD_KEESE_Z_AXIS',
    'qr_POLVIRE_NO_SHADOW',
    'qr_CONVEYORS_L1_L2',
    'qr_CUSTOMCOMBOS_EVERY_LAYER',
    'qr_SUBSCR_BACKWARDS_ID_ORDER',
    'qr_FASTCOUNTERDRAIN',
    'qr_OLD_LOCKBLOCK_COLLISION',
    'qr_DECO_2_YOFFSET',
    'qr_SCREENSTATE_80s_BUG',
    'qr_AUTOCOMBO_ANY_LAYER',
    'qr_GOHMA_UNDAMAGED_BUG',
    'qr_FFCPRELOAD_BUGGED_LOAD',
    'qr_SWITCHES_AFFECT_MOVINGBLOCKS',
    'qr_BROKEN_GETPIXEL_VALUE',
    'qr_NO_LIFT_SPRITE',
    'qr_OLD_SIDEVIEW_LANDING_CODE',
    'qr_OLD_FFC_SPEED_CAP',
    'qr_OLD_WIZZROBE_SUBMERGING',
    ('qr_OLD_FFC_FUNCTIONALITY', 50*8),
    'qr_OLD_SHALLOW_SFX',
    ('qr_PARSER_250DIVISION', 80*8),
    'qr_PARSER_NO_LOGGING',
    'qr_PARSER_SHORT_CIRCUIT',
    'qr_PARSER_BOOL_TRUE_DECIMAL',
    'qr_SPRITEXY_IS_FLOAT',
    'qr_PARSER_TRUE_INT_SIZE',
    'qr_WPNANIMFIX',
    'qr_NOSCRIPTSDURINGSCROLL',
    'qr_OLDSPRITEDRAWS',
    'qr_WEAPONSHADOWS',
    'qr_ITEMSHADOWS',
    'qr_OLDEWPNPARENT',
    'qr_OLDCREATEBITMAP_ARGS',
    'qr_OLDQUESTMISC',
    'qr_PARSER_FORCE_INLINE',
    'qr_CLEARINITDONSCRIPTCHANGE',
    'qr_NOFFCWAITDRAW',
    'qr_NOITEMWAITDRAW',
    'qr_TRACESCRIPTIDS',
    'qr_FIXDRUNKINPUTS',
    'qr_PARSER_BINARY_32BIT',
    'qr_ALWAYS_DEALLOCATE_ARRAYS',
    'qr_ONDEATH_RUNS_AFTER_DEATH_ANIM',
    'qr_DISALLOW_SETTING_RAFTING',
    'qr_WEAPONS_EXTRA_FRAME',
    'qr_250WRITEEDEFSCRIPT',
    'qr_SETENEMYWEAPONSPRITESONWPNCHANGE',
    'qr_BROKENCHARINTDRAWING',
    'qr_WRITING_NPC_WEAPON_UNIQUE_SPRITES',
    'qr_COMBOSCRIPTS_LAYER_0',
    'qr_COMBOSCRIPTS_LAYER_1',
    'qr_COMBOSCRIPTS_LAYER_2',
    'qr_COMBOSCRIPTS_LAYER_3',
    'qr_COMBOSCRIPTS_LAYER_4',
    'qr_COMBOSCRIPTS_LAYER_5',
    'qr_COMBOSCRIPTS_LAYER_6',
    'qr_OLD_INIT_SCRIPT_TIMING',
    'qr_DO_NOT_DEALLOCATE_INIT_AND_SAVELOAD_ARRAYS',
    'qr_BITMAP_AND_FILESYSTEM_PATHS_ALWAYS_RELATIVE',
    'qr_PARSER_STRINGSWITCH_INSENSITIVE',
    'qr_OLD_SLASHNEXT_SECRETS',
    'qr_STEP_IS_FLOAT',
    'qr_OLDMAPDATAFLAGS',
    'qr_OLD_PRINTF_ARGS',
    'qr_PASSIVE_SUBSCRIPT_RUNS_WHEN_GAME_IS_FROZEN',
    'qr_WRITE_ENTRYPOINTS_AFFECTS_HEROCLASS',
    'qr_LOG_INVALID_UID_LOAD',
    'qr_COMBODATA_INITD_MULT_TENK',
    'qr_ZS_NO_NEG_ARRAY',
])
